<?php

namespace TestBundle\Repository;

/**
 * VenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findVenteByUser($User){
        $query = $this->createQueryBuilder('a')
            ->andWhere('a.user =:user')
            ->setParameter('user', $User);
        return $query->getQuery()->getResult();
    }

    public  function findVenteByUserDate($User, $dateDebut, $dateFin){
        $query = $this->createQueryBuilder('a')
            ->andWhere('a.user =:user')
            ->andWhere('a.createdAt >:debut')
            ->andWhere('a.createdAt <:fin')
            ->setParameter('user', $User)
            ->setParameter('debut', $dateDebut)
            ->setParameter('fin', $dateFin);
        return $query->getQuery()->getResult();
    }
}
