test_produit:
    resource: "@TestBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

test_user:
    resource: "@TestBundle/Resources/config/routing/user.yml"
    prefix:   /user

test_vente:
    resource: "@TestBundle/Resources/config/routing/vente.yml"
    prefix:   /vente


test_homepage:
    path:     /
    defaults: { _controller: TestBundle:Default:index }


