vente_index:
    path:     /
    defaults: { _controller: "TestBundle:Vente:index" }
    methods:  GET

vente_show:
    path:     /{id}/show
    defaults: { _controller: "TestBundle:Vente:show" }
    methods:  GET

vente_new:
    path:     /new
    defaults: { _controller: "TestBundle:Default:vente" }
    methods:  [GET, POST]

vente_edit:
    path:     /{id}/edit
    defaults: { _controller: "TestBundle:Vente:edit" }
    methods:  [GET, POST]

vente_delete:
    path:     /{id}/delete
    defaults: { _controller: "TestBundle:Vente:delete" }
    methods:  DELETE
